TravelLibrary:
  mysql: 'default'
extendingTimeoutPeriodMills: 50000
joinTimeoutMills: 5000
flags:
  - 'enderchest'
  - 'equipments'
  #- 'level'
  #- 'exp'
  #- 'hungers'
  - 'inventory'
  - 'currentHealth'