main: com.minepalm.syncer.player.bukkit.PlayerSyncer
name: PlayerSyncer
author: Arkarang
version: 1.19-1.0.0
api-version: 1.19
depend:
  - PalmLibrary
  - BungeeJump
  - Syncer
commands:
  psalter:
    description: 'asdfasdf'
  pstest:
    description: 'test'